/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.parqueaderospopcliente.presentacion;

import co.unicauca.parqueaderospopcliente.negocio.EstadisticaIngreso;
import co.unicauca.parqueaderospopcliente.negocio.GestorEstadistica;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author danny
 */
public class GUIPrueba extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrueba
     */
    public GUIPrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar3 = new javax.swing.JProgressBar();
        jPanel = new javax.swing.JPanel();
        btnEstadistica = new javax.swing.JButton();
        jCalendar = new com.toedter.calendar.JDateChooser();
        jPBHora8 = new javax.swing.JProgressBar();
        jPBHora9 = new javax.swing.JProgressBar();
        jPBHora10 = new javax.swing.JProgressBar();
        jPBHora7 = new javax.swing.JProgressBar();
        jPBHora11 = new javax.swing.JProgressBar();
        jPBHora12 = new javax.swing.JProgressBar();
        jPBHora13 = new javax.swing.JProgressBar();
        jPBHora14 = new javax.swing.JProgressBar();
        jPBHora18 = new javax.swing.JProgressBar();
        jPBHora15 = new javax.swing.JProgressBar();
        jPBHora16 = new javax.swing.JProgressBar();
        jPBHora17 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        hora1 = new javax.swing.JLabel();
        hora2 = new javax.swing.JLabel();
        hora3 = new javax.swing.JLabel();
        hora4 = new javax.swing.JLabel();
        hora5 = new javax.swing.JLabel();
        hora6 = new javax.swing.JLabel();
        hora7 = new javax.swing.JLabel();
        hora8 = new javax.swing.JLabel();
        hora9 = new javax.swing.JLabel();
        hora10 = new javax.swing.JLabel();
        hora11 = new javax.swing.JLabel();
        hora12 = new javax.swing.JLabel();
        jPBHora19 = new javax.swing.JProgressBar();
        hora13 = new javax.swing.JLabel();
        Conteo1 = new javax.swing.JLabel();
        Conteo2 = new javax.swing.JLabel();
        Conteo3 = new javax.swing.JLabel();
        Conteo4 = new javax.swing.JLabel();
        Conteo5 = new javax.swing.JLabel();
        Conteo6 = new javax.swing.JLabel();
        Conteo7 = new javax.swing.JLabel();
        Conteo8 = new javax.swing.JLabel();
        Conteo9 = new javax.swing.JLabel();
        Conteo10 = new javax.swing.JLabel();
        Conteo11 = new javax.swing.JLabel();
        Conteo12 = new javax.swing.JLabel();
        Conteo13 = new javax.swing.JLabel();

        jProgressBar3.setOrientation(1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(204, 255, 255));

        btnEstadistica.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnEstadistica.setText("Imprimir");
        btnEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticaActionPerformed(evt);
            }
        });

        jPBHora8.setBackground(new java.awt.Color(255, 255, 255));
        jPBHora8.setMaximum(10);
        jPBHora8.setOrientation(1);

        jPBHora9.setBackground(new java.awt.Color(255, 255, 255));
        jPBHora9.setMaximum(10);
        jPBHora9.setOrientation(1);

        jPBHora10.setBackground(new java.awt.Color(255, 255, 255));
        jPBHora10.setMaximum(10);
        jPBHora10.setOrientation(1);

        jPBHora7.setBackground(new java.awt.Color(255, 255, 255));
        jPBHora7.setMaximum(10);
        jPBHora7.setOrientation(1);

        jPBHora11.setBackground(new java.awt.Color(255, 255, 255));
        jPBHora11.setMaximum(10);
        jPBHora11.setOrientation(1);

        jPBHora12.setBackground(new java.awt.Color(255, 255, 255));
        jPBHora12.setMaximum(10);
        jPBHora12.setOrientation(1);

        jPBHora13.setBackground(new java.awt.Color(255, 255, 255));
        jPBHora13.setMaximum(10);
        jPBHora13.setOrientation(1);

        jPBHora14.setBackground(new java.awt.Color(255, 255, 255));
        jPBHora14.setMaximum(10);
        jPBHora14.setOrientation(1);

        jPBHora18.setBackground(new java.awt.Color(255, 255, 255));
        jPBHora18.setMaximum(10);
        jPBHora18.setOrientation(1);

        jPBHora15.setBackground(new java.awt.Color(255, 255, 255));
        jPBHora15.setMaximum(10);
        jPBHora15.setOrientation(1);

        jPBHora16.setBackground(new java.awt.Color(255, 255, 255));
        jPBHora16.setMaximum(10);
        jPBHora16.setOrientation(1);

        jPBHora17.setBackground(new java.awt.Color(255, 255, 255));
        jPBHora17.setMaximum(10);
        jPBHora17.setOrientation(1);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 30)); // NOI18N
        jLabel1.setText("Estadistica Vehiculos Ingresados");

        hora1.setText("7");

        hora2.setText("8");

        hora3.setText("9");

        hora4.setText("10");

        hora5.setText("11");

        hora6.setText("12");

        hora7.setText("13");

        hora8.setText("14");

        hora9.setText("15");

        hora10.setText("16");

        hora11.setText("17");

        hora12.setText("18");

        jPBHora19.setBackground(new java.awt.Color(255, 255, 255));
        jPBHora19.setMaximum(10);
        jPBHora19.setOrientation(1);

        hora13.setText("19");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPBHora7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(hora1)
                                        .addGap(16, 16, 16)))
                                .addGap(18, 18, 18))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(Conteo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPBHora8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addComponent(hora2)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addComponent(Conteo2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(hora3)
                                            .addGap(52, 52, 52)
                                            .addComponent(hora4)
                                            .addGap(32, 32, 32))
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                            .addComponent(jPBHora9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jPBHora10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(Conteo3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Conteo4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)))
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(hora5))
                                    .addComponent(jPBHora11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                        .addComponent(Conteo5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(hora6))
                                    .addComponent(jPBHora12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                        .addComponent(Conteo6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPBHora13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(hora7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                        .addComponent(Conteo7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPBHora14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(hora8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                        .addComponent(Conteo8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(hora9))
                                    .addComponent(jPBHora15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                        .addComponent(Conteo9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)))
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(hora10))
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jPBHora16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                        .addComponent(Conteo10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPBHora17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(hora11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                        .addComponent(Conteo11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPBHora18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(hora12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                        .addComponent(Conteo12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPBHora19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Conteo13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanelLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(hora13))))))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1))))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnEstadistica)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEstadistica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Conteo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Conteo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Conteo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Conteo4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Conteo7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Conteo8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Conteo9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Conteo10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Conteo11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Conteo5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Conteo6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Conteo12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Conteo13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPBHora8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBHora9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBHora10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBHora7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBHora11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBHora12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBHora13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBHora14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBHora15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBHora16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBHora17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBHora18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBHora19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hora1)
                    .addComponent(hora2)
                    .addComponent(hora3)
                    .addComponent(hora4)
                    .addComponent(hora5)
                    .addComponent(hora6)
                    .addComponent(hora7)
                    .addComponent(hora8)
                    .addComponent(hora9)
                    .addComponent(hora10)
                    .addComponent(hora11)
                    .addComponent(hora12)
                    .addComponent(hora13))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticaActionPerformed
        // TODO add your handling code here:
        Conteo1.setText("0");
        Conteo2.setText("0");
        Conteo3.setText("0");
        Conteo4.setText("0");
        Conteo5.setText("0");
        Conteo6.setText("0");
        Conteo7.setText("0");
        Conteo8.setText("0");
        Conteo9.setText("0");
        Conteo10.setText("0");
        Conteo11.setText("0");
        Conteo12.setText("0");
        Conteo13.setText("0");
        GestorEstadistica gestorEst = new GestorEstadistica();
        List<EstadisticaIngreso> lista = new ArrayList();
        Date date = jCalendar.getDate();
        long d = date.getTime();
        java.sql.Date fecha = new java.sql.Date(d);
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String sFecha = df.format(fecha);

        try {
            lista = gestorEst.consultarEstadistica(sFecha);
            
        } catch (Exception e) {
            System.out.println(" ");
        }
        for (EstadisticaIngreso object : lista) {
            System.out.println(object.getFecha() + " " + object.getHora() + " " + object.getConteoTotal());
            if (object.getHora().equals("7")) {
                Conteo1.setText(object.getConteoTotal());
                jPBHora7.setValue(Integer.parseInt(object.getConteoTotal()));
            }
            if (object.getHora().equals("8")) {
                Conteo2.setText(object.getConteoTotal());
                jPBHora8.setValue(Integer.parseInt(object.getConteoTotal()));
            }
            if (object.getHora().equals("9")) {
                Conteo3.setText(object.getConteoTotal());
                jPBHora9.setValue(Integer.parseInt(object.getConteoTotal()));
            }
            if (object.getHora().equals("10")) {
                Conteo4.setText(object.getConteoTotal());
                jPBHora10.setValue(Integer.parseInt(object.getConteoTotal()));
            }
            if (object.getHora().equals("11")) {
                Conteo5.setText(object.getConteoTotal());
                jPBHora11.setValue(Integer.parseInt(object.getConteoTotal()));
            }
            if (object.getHora().equals("12")) {
                Conteo6.setText(object.getConteoTotal());
                jPBHora12.setValue(Integer.parseInt(object.getConteoTotal()));
            }
            if (object.getHora().equals("13")) {
                Conteo7.setText(object.getConteoTotal());
                jPBHora13.setValue(Integer.parseInt(object.getConteoTotal()));
            }
            if (object.getHora().equals("14")) {
                Conteo8.setText(object.getConteoTotal());
                jPBHora14.setValue(Integer.parseInt(object.getConteoTotal()));
            }
            if (object.getHora().equals("15")) {
                Conteo9.setText(object.getConteoTotal());
                jPBHora15.setValue(Integer.parseInt(object.getConteoTotal()));
            }
            if (object.getHora().equals("16")) {
                Conteo10.setText(object.getConteoTotal());
                jPBHora16.setValue(Integer.parseInt(object.getConteoTotal()));
            }
            if (object.getHora().equals("17")) {
                Conteo11.setText(object.getConteoTotal());
                jPBHora17.setValue(Integer.parseInt(object.getConteoTotal()));
            }
            if (object.getHora().equals("18")) {
                Conteo12.setText(object.getConteoTotal());
                jPBHora18.setValue(Integer.parseInt(object.getConteoTotal()));
            }
            if (object.getHora().equals("19")) {
                Conteo13.setText(object.getConteoTotal());
                jPBHora19.setValue(Integer.parseInt(object.getConteoTotal()));
            }
        }
    }//GEN-LAST:event_btnEstadisticaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Conteo1;
    private javax.swing.JLabel Conteo10;
    private javax.swing.JLabel Conteo11;
    private javax.swing.JLabel Conteo12;
    private javax.swing.JLabel Conteo13;
    private javax.swing.JLabel Conteo2;
    private javax.swing.JLabel Conteo3;
    private javax.swing.JLabel Conteo4;
    private javax.swing.JLabel Conteo5;
    private javax.swing.JLabel Conteo6;
    private javax.swing.JLabel Conteo7;
    private javax.swing.JLabel Conteo8;
    private javax.swing.JLabel Conteo9;
    private javax.swing.JButton btnEstadistica;
    private javax.swing.JLabel hora1;
    private javax.swing.JLabel hora10;
    private javax.swing.JLabel hora11;
    private javax.swing.JLabel hora12;
    private javax.swing.JLabel hora13;
    private javax.swing.JLabel hora2;
    private javax.swing.JLabel hora3;
    private javax.swing.JLabel hora4;
    private javax.swing.JLabel hora5;
    private javax.swing.JLabel hora6;
    private javax.swing.JLabel hora7;
    private javax.swing.JLabel hora8;
    private javax.swing.JLabel hora9;
    private com.toedter.calendar.JDateChooser jCalendar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jPBHora10;
    private javax.swing.JProgressBar jPBHora11;
    private javax.swing.JProgressBar jPBHora12;
    private javax.swing.JProgressBar jPBHora13;
    private javax.swing.JProgressBar jPBHora14;
    private javax.swing.JProgressBar jPBHora15;
    private javax.swing.JProgressBar jPBHora16;
    private javax.swing.JProgressBar jPBHora17;
    private javax.swing.JProgressBar jPBHora18;
    private javax.swing.JProgressBar jPBHora19;
    private javax.swing.JProgressBar jPBHora7;
    private javax.swing.JProgressBar jPBHora8;
    private javax.swing.JProgressBar jPBHora9;
    private javax.swing.JPanel jPanel;
    private javax.swing.JProgressBar jProgressBar3;
    // End of variables declaration//GEN-END:variables
}
