/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.parqueaderospopcliente.presentacion;

import co.unicauca.parqueaderospopcliente.negocio.GestorParqueadero;
import co.unicauca.parqueaderospopcliente.negocio.GestorRegVehiculo;
import co.unicauca.parqueaderospopcliente.negocio.GestorVehiculo;
import co.unicauca.parqueaderospopcliente.negocio.Parqueadero;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author danny
 */
public class GUIRegistrarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form GUIIngresarVehiculo
     */
    public GUIRegistrarVehiculo() {
        initComponents();
        GUIBuscarVehiculo busc = new GUIBuscarVehiculo();
        jtxtFPlaca.setText(busc.Placa);//asignamos una placa obtenida desde la vista de busqueda a la caja jtxtFPlaca
        jcmbNumCascos.setEnabled(false);//desactiva el numero de numero de cascos
        jtxtFCasillero.setEnabled(false);//desactiva la caja casillero
        jtxtFCasillero.setText("0");//asignamos un valor de 0 por defecto al casillero
        jtxtFPlaca.setEditable(false);//desactiva la caja placa
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbPlaca = new javax.swing.JLabel();
        jtxtFPlaca = new javax.swing.JTextField();
        jlbNumFicha = new javax.swing.JLabel();
        jtxtFNumFicha = new javax.swing.JTextField();
        jlbTipoVehiculo = new javax.swing.JLabel();
        jcmbTipoVehiculo = new javax.swing.JComboBox<>();
        jlbHoraFechaIng = new javax.swing.JLabel();
        jchbLlaves = new javax.swing.JCheckBox();
        jlbNumCascos = new javax.swing.JLabel();
        jcmbNumCascos = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtFCasillero = new javax.swing.JTextField();
        jtxtFHoraFecha = new javax.swing.JLabel();
        jblSalida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registar Vehiculo");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jlbPlaca.setText("Placa");

        jlbNumFicha.setText("Numero de ficha");

        jtxtFNumFicha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtFNumFichaKeyTyped(evt);
            }
        });

        jlbTipoVehiculo.setText("Tipo Vehiculo");

        jcmbTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto" }));
        jcmbTipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbTipoVehiculoActionPerformed(evt);
            }
        });

        jlbHoraFechaIng.setText("Hora y fecha entrada");

        jchbLlaves.setBackground(new java.awt.Color(204, 255, 255));
        jchbLlaves.setText("Deja llaves");

        jlbNumCascos.setText("Numero de cascos");

        jcmbNumCascos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));

        btnGuardar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setActionCommand("");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Casillero");

        jtxtFCasillero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtFCasilleroKeyTyped(evt);
            }
        });

        jtxtFHoraFecha.setText("-");
        jtxtFHoraFecha.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jtxtFHoraFechaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel2.setText("Entrada Vehiculo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jblSalida))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(jtxtFCasillero, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jlbHoraFechaIng)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtFHoraFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnGuardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegresar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlbTipoVehiculo)
                                            .addComponent(jlbNumFicha))
                                        .addGap(25, 25, 25))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbPlaca)
                                        .addGap(55, 55, 55)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtFNumFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcmbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jchbLlaves)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlbNumCascos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcmbNumCascos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNumFicha)
                    .addComponent(jtxtFNumFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbPlaca))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTipoVehiculo)
                    .addComponent(jcmbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbHoraFechaIng)
                    .addComponent(jtxtFHoraFecha))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchbLlaves)
                    .addComponent(jlbNumCascos)
                    .addComponent(jcmbNumCascos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFCasillero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jblSalida)
                .addGap(12, 12, 12)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//getters que nos daran los valores de algunos campos necesarios
    public String getJchbLlaves() {
        String llaves;
        if (jchbLlaves.isSelected()) {
            llaves = "SI";
        } else {
            llaves = "No";
        }
        return llaves;
    }

    public String getJcmbNumCascos() {
        int i = this.jcmbNumCascos.getSelectedIndex();
        return this.jcmbNumCascos.getItemAt(i);
    }

    public String getJcmbTipoVehiculo() {
        int i = this.jcmbTipoVehiculo.getSelectedIndex();
        return this.jcmbTipoVehiculo.getItemAt(i);
    }

    public String getJtxtFCasillero() {
        return this.jtxtFCasillero.getText();
    }

    public String getJtxtFHoraFecha() {
        return this.jtxtFHoraFecha.getText();
    }

    public String getJtxtFNumFicha() {
        return this.jtxtFNumFicha.getText();
    }

    public String getJtxtFPlaca() {
        return this.jtxtFPlaca.getText();
    }
//Metodo para limpiar las cajas de texto
    public void limpiar() {
        jtxtFNumFicha.setText(null);
        jtxtFPlaca.setText(null);
        jcmbTipoVehiculo.setSelectedItem("Carro");
        //frmRegVehi.jtxtFHoraFecha.setText(" ");

        Date date = new Date();
        DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        jtxtFHoraFecha.setText(hourFormat.format(date) + "  " + dateFormat.format(date));

        jchbLlaves.setSelected(false);
        jtxtFCasillero.setText("0");
    }
//Metodo que se encarga de guardar un vehiculo cuando le den click al boton guardar 
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (jtxtFNumFicha.getText().isEmpty() || jtxtFPlaca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Numero de ficha o el campo placa no pueden estar vacios");

        } else {
            GUIIniciarSesion ini = new GUIIniciarSesion();
            GestorRegVehiculo reg = new GestorRegVehiculo();
            GestorVehiculo vehi = new GestorVehiculo();
            GestorParqueadero gestorPa = new GestorParqueadero();
            Parqueadero parqueadero = new Parqueadero();
            //sacamos los valores de las cajas de texto 
            String NumFicha = jtxtFNumFicha.getText();
            String NumPlaca = jtxtFPlaca.getText();
            String TipoVehiculo = jcmbTipoVehiculo.getSelectedItem().toString();
            String HoraYFechaEntrada = jtxtFHoraFecha.getText();
            String Llaves;
            String EstadoVehiculo = "Ingresado";
            if (jchbLlaves.isSelected()) {
                Llaves = "si";
            } else {
                Llaves = "no";
            }
            String NumCascos = jcmbNumCascos.getSelectedItem().toString();
            String NitParqueadero = ini.atrNit;
            String Casillero;
            if (jtxtFCasillero.getText() == null) {
                Casillero = "0";
            } else {
                Casillero = jtxtFCasillero.getText();
            }
            String Usuario = ini.atrFuncionario;
            String HoraFechaSalida = jblSalida.getText();
            
            try{
                parqueadero = gestorPa.consultarParqueadero(Usuario);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "No se encontro el registro");
            }
            
            String numeroLibres = parqueadero.getPuestosLibres();
            int Libres = Integer.parseInt(numeroLibres);

            if (Libres == 0) {
                JOptionPane.showMessageDialog(null, "NO hay puestos disponibles");
            } else {
                try {
                    reg.ingresarRegVehiculo(NumFicha, NumPlaca, TipoVehiculo, HoraYFechaEntrada, EstadoVehiculo, Llaves, NumCascos, NitParqueadero, Casillero, Usuario, HoraFechaSalida);
                    gestorPa.actualizarIngreso(NitParqueadero);
                    JOptionPane.showMessageDialog(null, "Registro guardado");
                    limpiar();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al guardar");
                }
            }
            dispose();
            GUIBuscarVehiculo busc = new GUIBuscarVehiculo();
            busc.setVisible(true);
            busc.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    //Metodo que desactiva los campos numero de cascos y numero de casillero si es un carro y los activa si es una moto 
    private void jcmbTipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbTipoVehiculoActionPerformed
        // TODO add your handling code here:
        if (jcmbTipoVehiculo.getSelectedItem().toString().equals("Carro")) {
            jcmbNumCascos.setEnabled(false);
            jtxtFCasillero.setEnabled(false);
        } else {
            jcmbNumCascos.setEnabled(true);
            jtxtFCasillero.setEnabled(true);
        }
    }//GEN-LAST:event_jcmbTipoVehiculoActionPerformed

    //evita que se ingresen caracteres diferentes a los numeros en el numero de ficha
    private void jtxtFNumFichaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFNumFichaKeyTyped

        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9')
            evt.consume();
    }//GEN-LAST:event_jtxtFNumFichaKeyTyped
    //evita que se ingresen caracteres diferentes a los numeros en el numero de casillero
    private void jtxtFCasilleroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFCasilleroKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9')
            evt.consume();
    }//GEN-LAST:event_jtxtFCasilleroKeyTyped
//regresa a la pagina de busqueda 
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
        GUIBuscarVehiculo busc = new GUIBuscarVehiculo();
        busc.setVisible(true);
        busc.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegresarActionPerformed
// asignamos la hora actual del sistema a el jtxtFHoraFecha
    private void jtxtFHoraFechaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jtxtFHoraFechaAncestorAdded
        Date date = new Date();
        DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        jtxtFHoraFecha.setText(dateFormat.format(date) + " " + hourFormat.format(date));
    }//GEN-LAST:event_jtxtFHoraFechaAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRegistrarVehiculo().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblSalida;
    private javax.swing.JCheckBox jchbLlaves;
    private javax.swing.JComboBox<String> jcmbNumCascos;
    private javax.swing.JComboBox<String> jcmbTipoVehiculo;
    private javax.swing.JLabel jlbHoraFechaIng;
    private javax.swing.JLabel jlbNumCascos;
    private javax.swing.JLabel jlbNumFicha;
    private javax.swing.JLabel jlbPlaca;
    private javax.swing.JLabel jlbTipoVehiculo;
    private javax.swing.JTextField jtxtFCasillero;
    private javax.swing.JLabel jtxtFHoraFecha;
    private javax.swing.JTextField jtxtFNumFicha;
    private javax.swing.JTextField jtxtFPlaca;
    // End of variables declaration//GEN-END:variables
}
