/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.parqueaderospopcliente.presentacion;

import co.unicauca.parqueaderospopcliente.negocio.GestorParqueadero;
import co.unicauca.parqueaderospopcliente.negocio.GestorRegVehiculo;
import co.unicauca.parqueaderospopcliente.negocio.GestorTarifa;
import co.unicauca.parqueaderospopcliente.negocio.RegVehiculo;
import co.unicauca.parqueaderospopcliente.negocio.Tarifa;
import java.text.ParseException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author danny
 */
public class GUISalidaVehiculo extends javax.swing.JFrame {

    /**
     * Creamos atributos staticos publicos para que puedan ser utilizados por otras vistas 
     */
    
    public int atrHoras;
    public int atrMinutos;
    
    public GUISalidaVehiculo() {
      initComponents();
      jtxtPlaca.setEditable(false);//deshabilitamos la caja jtxtPlaca
      GUIBuscarVehiculo Buscar = new GUIBuscarVehiculo();
      jtxtPlaca.setText(Buscar.Placa);//asignamos el valor de Buscar.placa a el campo jtxtPlaca
      jtxtFTipoVehiculo.setText(Buscar.atrTipoVehiculo);//asignamos el valor de Buscar.atrTipoVehiculo a la caja  jtxtFTipoVehiculo
      jtxtFTipoVehiculo.setEditable(false);// deshabilitamos la caja  jtxtFTipoVehiculo
      lblHoraYFechaEntrada.setText(Buscar.HoraFechaEntrada);//asignamos el valor de Buscar.HoraFechaEntrada a el label lblHoraYFechaEntrada
      jtxtTiempo.setEditable(false);// deshabilitamos la caja   jtxtTiempo
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblPlaca = new javax.swing.JLabel();
        jlblEntrada = new javax.swing.JLabel();
        jlblSalida = new javax.swing.JLabel();
        jlblTiempo = new javax.swing.JLabel();
        jLblValor = new javax.swing.JLabel();
        btnRetirar = new javax.swing.JButton();
        lblHoraYFechaEntrada = new javax.swing.JLabel();
        lblHoraYFechaSalida = new javax.swing.JLabel();
        jtxtPlaca = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        jtxtTiempo = new javax.swing.JTextField();
        jtxtFValorPagar = new javax.swing.JTextField();
        jRBPerdida = new javax.swing.JRadioButton();
        jlbTipoVehiculo = new javax.swing.JLabel();
        jtxtFTipoVehiculo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Salida Vehiculo");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setToolTipText("");

        jlblPlaca.setText("Placa");

        jlblEntrada.setText("Fecha y Hora Entrada");

        jlblSalida.setText("Fecha Y Hora Salida");

        jlblTiempo.setText("Tiempo Transcurrido");

        jLblValor.setText("Valor");

        btnRetirar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnRetirar.setText("Retirar");
        btnRetirar.setToolTipText("");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        lblHoraYFechaEntrada.setText("-");
        lblHoraYFechaEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblHoraYFechaEntradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblHoraYFechaSalida.setText("-");
        lblHoraYFechaSalida.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblHoraYFechaSalidaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnRegresar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jtxtTiempo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtTiempoMouseClicked(evt);
            }
        });

        jtxtFValorPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtFValorPagarMouseClicked(evt);
            }
        });

        jRBPerdida.setBackground(new java.awt.Color(204, 255, 255));
        jRBPerdida.setText("Perdida Ficha");

        jlbTipoVehiculo.setText("Tipo de Vehiculo");

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel1.setText("Salida Vehiculo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblSalida)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jlbTipoVehiculo))
                            .addComponent(jlblTiempo)
                            .addComponent(jlblEntrada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHoraYFechaEntrada)
                            .addComponent(lblHoraYFechaSalida)
                            .addComponent(jtxtTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jtxtPlaca)
                            .addComponent(jtxtFTipoVehiculo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLblValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(jtxtFValorPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jRBPerdida))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jlblPlaca)))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRetirar)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPlaca)
                    .addComponent(jtxtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTipoVehiculo)
                    .addComponent(jtxtFTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraYFechaEntrada)
                    .addComponent(jlblEntrada))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSalida)
                    .addComponent(lblHoraYFechaSalida))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTiempo))
                .addGap(18, 18, 18)
                .addComponent(jRBPerdida)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFValorPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblValor))
                .addGap(18, 18, 18)
                .addComponent(btnRetirar)
                .addGap(11, 11, 11)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void limpiar(){
        //lblHoraYFechaEntrada.setText(null);
        lblHoraYFechaSalida.setText(null);
        jtxtPlaca.setText(null);
        jtxtFValorPagar.setText(null);
        
    }
    //Metodo que actualiza el estado y fecha de salida del vehiculo cuando se le de al boton retirar 
    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        
        GUIIniciarSesion iniciar = new GUIIniciarSesion();
        GestorRegVehiculo gestorR = new GestorRegVehiculo();
        GestorParqueadero gestorPar = new GestorParqueadero();
        String Placa = jtxtPlaca.getText();
        String NitParqueadero = iniciar.atrNit;
        String HoraFechaSalida = lblHoraYFechaSalida.getText();

        if (jtxtFValorPagar.getText().isEmpty() || jtxtTiempo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No pueden quedar campos vacios");
        } else {
            try {
                gestorR.actualizarRegVehiculo(Placa, HoraFechaSalida);
                gestorPar.actualizarSalida(NitParqueadero);
                JOptionPane.showMessageDialog(null, "Vehiculo retirado");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al retirar");
            }
            limpiar();
            dispose();
            GUIBuscarVehiculo bus = new GUIBuscarVehiculo();
            bus.setVisible(true);
            bus.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void lblHoraYFechaEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblHoraYFechaEntradaAncestorAdded
         
    }//GEN-LAST:event_lblHoraYFechaEntradaAncestorAdded

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        dispose();
        GUIBuscarVehiculo bus = new GUIBuscarVehiculo();
        bus.setVisible(true);
        bus.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegresarActionPerformed
// calcula el tiempo que estuvo un vehiculo en el parqueadero
    private void jtxtTiempoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtTiempoMouseClicked
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd H:m:s");
        int diferencia;
        int dias = 0;
        int horas = 0;
        int minutos = 0;
        try {
            Date fechaInicial = dateFormat.parse(lblHoraYFechaEntrada.getText());
            Date fechaFinal = dateFormat.parse(lblHoraYFechaSalida.getText());
            diferencia = (int) ((fechaFinal.getTime() - fechaInicial.getTime()) / 1000);

            if (diferencia > 86400) {
                dias = (int) Math.floor(diferencia / 86400);
                diferencia = diferencia - (dias * 86400);
            }
            if (diferencia > 3600) {
                horas = (int) Math.floor(diferencia / 3600);
                diferencia = diferencia - (horas * 3600);
            }
            if (diferencia > 60) {
                minutos = (int) Math.floor(diferencia / 60);
                diferencia = diferencia - (minutos * 60);
            }
            
            jtxtTiempo.setText("Horas:" + horas + " " + "Minutos:"+minutos);
        } catch (ParseException ex) {
            Logger.getLogger(GUISalidaVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        atrHoras = horas;
        atrMinutos = minutos;

    }//GEN-LAST:event_jtxtTiempoMouseClicked
//asignamos la hora actual del sistema a el label lblHoraYFechaSalida
    private void lblHoraYFechaSalidaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblHoraYFechaSalidaAncestorAdded
        // TODO add your handling code here:
        Date date = new Date();
        DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        lblHoraYFechaSalida.setText( dateFormat.format(date) + "  " + hourFormat.format(date));
    }//GEN-LAST:event_lblHoraYFechaSalidaAncestorAdded
//sacamos el valor a pagar del vehiculo si es carro o moto,ademas de un recargo si perdio su ficha 
    private void jtxtFValorPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtFValorPagarMouseClicked
        // TODO add your handling code here:
        int multa;
        int tarifaPagar;
        int valorPagar;
        String aHoras = Integer.toString(atrHoras);
        String aMinutos = Integer.toString(atrMinutos);
        GestorTarifa gestorT = new GestorTarifa();
        Tarifa tari = new Tarifa();
        if (jtxtFTipoVehiculo.getText().equals("Carro")) {
            try {
                tari = gestorT.consultarTarifa(aHoras, aMinutos);
                System.out.println("Consulta realizada");
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            if (jtxtFTipoVehiculo.getText().equals("Moto")) {
                try {
                    tari = gestorT.consultarTarifaMotos(aHoras, aMinutos);
                    System.out.println("Consulta realizada");
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }

        if (jRBPerdida.isSelected()) {
            multa = 5000;
            tarifaPagar = Integer.parseInt(tari.getValorTotal());
            valorPagar = multa + tarifaPagar;
            jtxtFValorPagar.setText("$" + valorPagar);
        } else {
            jtxtFValorPagar.setText("$" + " " + tari.getValorTotal());
        }
    }//GEN-LAST:event_jtxtFValorPagarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISalidaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISalidaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISalidaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISalidaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISalidaVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBPerdida;
    private javax.swing.JLabel jlbTipoVehiculo;
    private javax.swing.JLabel jlblEntrada;
    private javax.swing.JLabel jlblPlaca;
    private javax.swing.JLabel jlblSalida;
    private javax.swing.JLabel jlblTiempo;
    private javax.swing.JTextField jtxtFTipoVehiculo;
    private javax.swing.JTextField jtxtFValorPagar;
    private javax.swing.JTextField jtxtPlaca;
    private javax.swing.JTextField jtxtTiempo;
    javax.swing.JLabel lblHoraYFechaEntrada;
    private javax.swing.JLabel lblHoraYFechaSalida;
    // End of variables declaration//GEN-END:variables
}
